### ISSUE TITLE
Airdrop Workflow - File Action

### ISSUE THREAD

**Issue by chrisspiegl** [alanhg/alfred-workflows#15]
Hello @alanhg, 

I just found your airdrop workflow and was wondering if you are planning to bring back the file action as well?
Or do I have to set that up myself?
Any updates on the workflow so far?

I'd love the ability to send files via file actions from the finder.

Thanks and I am looking forward to hearing from you,
Chris

**Comment by alanhg** [comment]
> Hello @alanhg,
> 
> I just found your airdrop workflow and was wondering if you are planning to bring back the file action as well?
> Or do I have to set that up myself?
> Any updates on the workflow so far?
> 
> I'd love the ability to send files via file actions from the finder.
> 
> Thanks and I am looking forward to hearing from you,
> Chris

Good idea, I realized, update it and have a try.

## screenshot

https://github.com/alanhg/alfred-workflows/blob/master/airdrop/screenshot2.gif

**Comment by chrisspiegl** [comment]
Awesome, I'll update once I tested.
