### ISSUE TITLE
Share via File Action has Error (`Share` menu item index not correct)

### ISSUE THREAD

**Issue by chrisspiegl** [alanhg/alfred-workflows#16]
I tried the share file action and it shows an error.
Apparently the index of the `Share` menu item is different on your system to mine.

I have attached the error and my finder menu.

Maybe this can be done index agnostic so that it does not need a number index?

![Screen Shot 2021-01-08 at 11 54 04](https://user-images.githubusercontent.com/1096384/104007435-3629d980-51a8-11eb-93e5-350d780e9368.png)

![Screen Shot 2021-01-08 at 11 52 54](https://user-images.githubusercontent.com/1096384/104007331-11cdfd00-51a8-11eb-9968-d5431096b485.png)

**Comment by alanhg** [comment]
> I tried the share file action and it shows an error.
> Apparently the index of the `Share` menu item is different on your system to mine.
> 
> I have attached the error and my finder menu.
> 
> Maybe this can be done index agnostic so that it does not need a number index?
> 
> ![Screen Shot 2021-01-08 at 11 54 04](https://user-images.githubusercontent.com/1096384/104007435-3629d980-51a8-11eb-93e5-350d780e9368.png)
> 
> ![Screen Shot 2021-01-08 at 11 52 54](https://user-images.githubusercontent.com/1096384/104007331-11cdfd00-51a8-11eb-9968-d5431096b485.png)

What's your system version?

**Comment by chrisspiegl** [comment]
I am running macOS Big Sur Version 11.2 Beta (20D5029f)

**Comment by alanhg** [comment]
I currently don’t have a machine with this os version, so I can’t adapt it, and you need to debug it yourself.

you can modify find airdrop menu script.
