### ISSUE TITLE
印象笔记的alfredworkflow 运行ensync 报错 ERROR: 印象笔记[Run Script] 31:42: execution error: 变量“synchronize”没有定义。 (-2753)

### ISSUE THREAD

**Issue by FengZhengHai** [alanhg/alfred-workflows#21]
ERROR: 印象笔记[Run Script] 31:42: execution error: 变量“synchronize”没有定义。 (-2753)
![image](https://user-images.githubusercontent.com/22488139/108967205-26b01280-76ba-11eb-95fd-dfa0cbde0534.png)

**Comment by alanhg** [comment]
fixed. install the latest version.
