### ISSUE TITLE
surge Alfred workflow 报错

### ISSUE THREAD

**Issue by joescon** [alanhg/alfred-workflows#23]
首先感谢开发了这个workflow，我能找到的全网唯一的surge workflow了。
但根据教程我还是没能成功使用。

请问能否帮忙诊断下是什么问题？
感谢。

Alfred 4.32
surge workflow v1.4.0

情况：
surge http API已经开启，Alfred输入surge的时候，出现you should enable http API的提示。

Alfred log如下：

Local (192.168.70.101:50457)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1064:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:65959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:65959) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:65959) UnhandledPromiseRejectionWarning: Error: connect EHOSTUNREACH 0.0.24.8:80 - Local (192.168.70.101:50458)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1064:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
(node:65959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:65959) UnhandledPromiseRejectionWarning: ReferenceError: reject is not defined
    at /Users/joe/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1C5BA183-0195-4414-9D6B-36DA922CAF19/index.js:59:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:65959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:65959) UnhandledPromiseRejectionWarning: ReferenceError: reject is not defined
    at /Users/joe/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1C5BA183-0195-4414-9D6B-36DA922CAF19/index.js:72:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:65959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:65959) UnhandledPromiseRejectionWarning: ReferenceError: reject is not defined
    at /Users/joe/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1C5BA183-0195-4414-9D6B-36DA922CAF19/index.js:85:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:65959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:65959) UnhandledPromiseRejectionWarning: ReferenceError: reject is not defined
    at /Users/joe/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1C5BA183-0195-4414-9D6B-36DA922CAF19/index.js:26:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:65959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
[16:21:36.805] Surge[Script Filter] {"items":[{"title":"You should enable HTTP API","subtitle":"Press enter to config","arg":"httpApi"}]}
[16:21:39.032] Surge[Script Filter] Processing complete
[16:21:39.064] Surge[Script Filter] Passing output 'httpApi' to Conditional
[16:21:39.065] Surge[Conditional] Processing complete
[16:21:39.067] Surge[Conditional] Passing output 'httpApi' to Launch Apps / Files

**Comment by alanhg** [comment]
有看资料，开启API配置吗？

配置文件中增加如下配置

http-api = examplekey@0.0.0.0:6171

https://1991421.cn/2020/11/16/a12a6619/
