### ISSUE TITLE
Request to add OneUpdater in workflows

### ISSUE THREAD

**Issue by augusl** [alanhg/alfred-workflows#254]
OneUpdater is an updater you can plug with minimal configuration into workflows, to keep them up-to-date in users’ machines.

https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater

**Comment by alanhg** [comment]
I've started integrating update functionality into each workflow, which will be incrementally added.

For those that are already supported, instructions are provided in readme.


![image](https://user-images.githubusercontent.com/9245110/169540118-8d0d0ca6-cfd7-4f11-887b-cddc833d42a7.png)


![image](https://user-images.githubusercontent.com/9245110/169540163-8a643780-f3a0-4120-8a46-437f9dba6373.png)


![image](https://user-images.githubusercontent.com/9245110/169540337-a4e3bb66-150c-4b6b-92de-c2d64aa25a91.png)
