### ISSUE TITLE
[Req] 2FA Read Code: Mark message as read after grabbing code

### ISSUE THREAD

**Issue by madmaximux** [alanhg/alfred-workflows#264]
Workflow Name: 2FA Read Code

**Is your feature request related to a problem? Please describe.**
Not sure if this could be programmed but would be cool if we could mark the message as read after grabbing the code. 

<img width="42" alt="image" src="https://user-images.githubusercontent.com/68623691/170884161-12a13cf4-beb3-4841-8495-2ea779edb266.png">

**Describe the solution you'd like**
Mark item as read so notification icon goes away.

**Comment by alanhg** [comment]
There's no great way to do it, so you can't do it.

1. https://stackoverflow.com/questions/53675512/how-to-mark-messages-as-read-with-apple-script

![image](https://user-images.githubusercontent.com/9245110/171002573-2e247fb0-28d3-43d8-bd59-50bc64247a35.png)
