### ISSUE TITLE
You should enable HTTP API

### ISSUE THREAD

**Issue by harisonkhlil** [alanhg/alfred-workflows#289]
我确定我百分百设置了 http api 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/70578017/182761346-cc78e747-7d9b-420d-945f-a79dd25f6af1.png">

并且 alfred 插件设置也修改了
<img width="805" alt="image" src="https://user-images.githubusercontent.com/70578017/182761288-a55dd24e-ef0e-4d59-b175-12ed14b42216.png">

但是仍旧显示这个
<img width="773" alt="image" src="https://user-images.githubusercontent.com/70578017/182761382-63d2ad52-08d7-4e2a-b285-d2277f7bba4f.png">

**Comment by alanhg** [comment]
> 我确定我百分百设置了 http api <img alt="image" width="701" src="https://user-images.githubusercontent.com/70578017/182761346-cc78e747-7d9b-420d-945f-a79dd25f6af1.png">

hi，workflow开启下debug 看下？

**Comment by harisonkhlil** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/70578017/182766174-1df1d6bd-8c07-4210-8165-f4692c80c973.png">

**Comment by alanhg** [comment]
1. 我更新了下该workflow，针对异常信息暴露了下，这样方便诊断问题。
2. 无论是 HTTP API请求没通，或者本身workflow执行上有报错，可以方便的看出来，Command L放大展示，Command C也方便拷贝出来看下具体怎么回事。

![image](https://user-images.githubusercontent.com/9245110/183236701-c262467b-401e-44ec-8a39-4990f4f50003.png)

**Comment by harisonkhlil** [comment]
没有看到更新啊
![image](https://user-images.githubusercontent.com/70578017/183243041-068fd238-d3fa-4f0a-ace2-3129551a31c9.png)

**Comment by alanhg** [comment]
> 没有看到更新啊 ![image](https://user-images.githubusercontent.com/70578017/183243041-068fd238-d3fa-4f0a-ace2-3129551a31c9.png)

再看下

**Comment by harisonkhlil** [comment]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/70578017/183243949-9f539bbd-bf88-4bce-8b4d-344ea9c6a0c1.png">
我明明设置的是这个啊
<img width="871" alt="image" src="https://user-images.githubusercontent.com/70578017/183243963-239a98dc-ce27-4664-9390-50bf9fbad6a1.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/70578017/183244028-c525eaf1-c084-4def-b01d-86743d367d74.png">

**Comment by alanhg** [comment]
异常的直接原因在错误里已经提示
![image](https://user-images.githubusercontent.com/9245110/183244685-ed81beff-7f83-4b26-8c72-582b3db9b756.png)

so，自行去排查本地网络中间，哪里加了代理之类从而造成服务不通。

个人理解，非Alfred-Workflow层面问题。

**Comment by alanhg** [comment]
所以直接原因是workflow访问本地的6171web服务，提示却是本地443端口拒绝访问。

你看下本地443端口是谁占用的。

这种问题更多还是靠自己去排查了。

**Comment by alanhg** [comment]
@harisonkhlil 

## 应该是你的Surge没有走代理的问题

解决办法选择如下其一

1. Surge开启系统代理+增强模式
2. Alfred开启代理，使其走系统代理


![image](https://user-images.githubusercontent.com/9245110/183254657-fe8d2971-9850-4ba7-9db3-a4c4b6eb7fad.png)

![image](https://user-images.githubusercontent.com/9245110/183254670-12d6c7ff-95c0-4e94-97a0-2b59316bfbe5.png)
