### ISSUE TITLE
Airdrop universal action not working

### ISSUE THREAD

**Issue by goodgoed** [alanhg/alfred-workflows#297]
**Describe the bug**
Airdrop workflow does not work in universal action. If any file is selected, this workflow will try to share that file, even if I try sharing a different file using universal action. 

**Version Info (please complete the following information):**
- MacOS Version: Monterery 12.5.1
- Alfred Version: v5.0.2
- Workflow Name & Version: Airdrop

**To Reproduce**
1. Select any file or folder in Alfred
2. Click the right arrow to open universal action
3. Choose 'Share files with Airdrop'
4. Nothing happens

**Expected behavior**
If I select a file or folder and then run Alfred workflow, it works smoothly. I expect universal action to be working the same as that. 

**Screenshots**
<img width="843" alt="1" src="https://user-images.githubusercontent.com/42894106/188562229-9cc616a9-b76d-4622-a506-95604c425e7e.png">

**Additional context**
I think the problem is with the selection part. The file is not selected. Finder is not opened either.

**Comment by alanhg** [comment]
Nice question

My previous idea was for the user to select a file from Finder and trigger the action.

But your needs are reasonable. I have supported this scenario.

just have a try.
