### ISSUE TITLE
[Bug]: universal action doesn't respond

### ISSUE THREAD

**Issue by vanwoods** [alanhg/alfred-workflows#311]
### Describe the bug

There is no action when trying to activate this in universal actions. Any chance to know what could be the issue?

### MacOS Version

macOS 12 Monterey

### Alfred Version

5.0.4

### Workflow Name

Airdrop

**Comment by alanhg** [comment]
@vanwoods 
##  Any chance to know what could be the issue?

![image](https://user-images.githubusercontent.com/9245110/199514343-2222ade9-7356-4e07-8727-cd057086174f.png)

**Comment by vanwoods** [comment]
Hi Alan.He,

Thanks for reminding for the debugger output. Below the error I’m getting this back from the debugger:
> [15:41:07.383] ERROR: Airdrop[Run Script] /Users/patrick/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/9FE38F2A-0AA7-43CE-BD03-18619326CFDF:78:119: execution error: System Events got an error: button 1 or toolbar 1 or window 1 of process "Finder" whose description = "Share" could not be requested. Invalid index. (-1719)

Hope you can tell what’s going wrong?

Thanks in advance!

---------------------------

Regards,
Patrick
On 2 Nov 2022, 15:23 +0100, Alan.He ***@***.***>, wrote:
	@vanwoods
Any chance to know what could be the issue?

**Comment by alanhg** [comment]
> button 1 or toolbar 1 or window 1 of process "Finder" whose description = "Share" could not be requested. Invalid index

You need to see if there is this menu on the UI. Maybe your system locale is not `en`

**Comment by vanwoods** [comment]
Hi,

I changed the system language to English. But unfortunately I’m getting the same error message.
> [17:55:03.740] ERROR: Airdrop[Run Script] /Users/patrick/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/4E370D6A-D5AB-45CB-B14A-5B7BB1CC81CE:78:119: execution error: System Events got an error: Can’t get button 1 of toolbar 1 of window 1 of process "Finder" whose description = "Share". Invalid index. (-1719)
I’m not getting a UI menu.

Is there anything else what I can check to fix this?

---------------------------

Regards,
Patrick

**Comment by alanhg** [comment]
@vanwoods 

Is it convenient to provide a screen recording?

**Comment by vanwoods** [comment]
Thanks for getting back to me. I tried a different computer and it has the same issue and debugger output.

Attached is the screen recording.


---------------------------

Regards,
Patrick

**Comment by alanhg** [comment]
???Attached is the screen recording.  where?

**Comment by vanwoods** [comment]
It is attached in the email!

---------------------------

Groetjes,
Patrick

**Comment by augusl** [comment]
After macOS upgraded to Ventura, I also encountered this problem

**Comment by alanhg** [comment]
> After macOS upgraded to Ventura, I also encountered this problem

1. I haven't upgraded my new system at the moment, so I can't test verify the issue.
2. The workflow relies on the UI, so the cause of the problem should be here.

**Comment by katelynnbarlowe** [comment]
Would love some movement on this. Doesn't work for me either.

**Comment by alanhg** [comment]
## update
root cause is os ui change.
![image](https://user-images.githubusercontent.com/9245110/210193159-be3bed0c-ba58-4bfe-b47a-f2ae435861d7.png)

**Comment by vanwoods** [comment]
Hi, 

Thanks for the feedback. What can I do to fix this, I don't get it?

**Comment by alanhg** [comment]
for Sonoma User, just have a try. download the latest workflow.


I found that the AppleScript documentation is too scarce. I really can't solve the more advanced menu automation operations, so I'm adopting a compromise solution here.

You need to manually drag and drop AirDrop into the toolbar. This way, the workflow can be operated conveniently. For specific setup instructions, please refer to the documentation I have posted.

![image](https://github.com/alanhg/alfred-workflows/assets/9245110/2eef9061-61bf-44bc-8475-b4fb220d579e)
https://github.com/alanhg/alfred-workflows/tree/master/airdrop#sonoma-need
