### ISSUE TITLE
[Bug]: AppID

### ISSUE THREAD

**Issue by ITRecords38** [alanhg/alfred-workflows#336]
### Describe the bug

Hi,

when I query the appid command it returns to the alfred search part.

If you can help me. thanks in advance

### Workflow Name

AppID

### Alfred Version

5.1 (2129)

### MacOS Version

macOS 13 Ventura

### MacOS Locale

None

**Comment by ITRecords38** [comment]
small correction concerns sorry the request "av"

**Comment by ITRecords38** [comment]
result of file log

  status: 1,
  signal: null,
  output: [
    null,
    '/Applications/Utilities/Feedback Assistant.app: could not find /Applications/Utilities/Feedback Assistant.app.\n',
    ''
  ],
  pid: 86797,
  stdout: '/Applications/Utilities/Feedback Assistant.app: could not find /Applications/Utilities/Feedback Assistant.app.\n',
  stderr: ''
}

Node.js v19.8.1

**Comment by alanhg** [comment]
so another app, like Google Chrome, it's ok?

**Comment by ITRecords38** [comment]
Hi @alanhg 

Thank you for return. whatever the applications it does not work but since yesterday it works.

1. I had manually deleted "the Feedback Assistant.app" 
2. and with the 13.3.1 update released last night by apple it works again after reinstalling the application

weird that the request a need to have this app. This can help you if you want to make a correction.

<img width="1344" alt="Screenshot" src="https://user-images.githubusercontent.com/19632490/230707200-208ed682-a142-4d90-b4cf-00a4aa572da8.png">
