### ISSUE TITLE
[Bug]: 2FA不能读取三位数验证码

### ISSUE THREAD

**Issue by 5mdld** [alanhg/alfred-workflows#339]
### Describe the bug

附短信原文：

『　267　』
セキュリティ番号入力画面で、上記3桁の数字を入力してください。
有効期限：2023/04/11 14:47

### Workflow Name

2FA-Read Code

### Alfred Version

5.0.6 [2110]

### MacOS Version

macOS 13 Ventura

### Mac Chip

Apple Silicon (like M1, M2)

### MacOS Locale

CN-中文

**Comment by alanhg** [comment]
已调整支持了3位，thanks.
