### ISSUE TITLE
[Bug]: I installed chromeprofile in alfred 5.1 but it is not working.

### ISSUE THREAD

**Issue by nishanrai** [alanhg/alfred-workflows#369]
### Describe the bug

I installed chromeprofile in alfred 5.1 but it is not working. 

### Workflow Name

Open Chrome Profile

### Alfred Version

v5.1

### MacOS Version

macOS 13 Ventura

### Mac Chip

Intel

### MacOS Locale

None

-----

Workflow Homepage is 👉 [Open Chrome Profile](https://github.com/alanhg/alfred-workflows/tree/master/open-chrome-profile)

**Comment by alanhg** [comment]
I think you should debug it. and post screenshot or debug info.


![image](https://github.com/alanhg/alfred-workflows/assets/9245110/586a8883-2bb0-495c-b24b-a8c746301a57)

## how to debug
https://www.alfredapp.com/help/workflows/advanced/debugger/


If there are no specific screenshots or error messages, I can only guess. If it's not certain or cannot be reproduced, I can only close these issues.
