### ISSUE TITLE
[虫子]：An error was encountered: this operation could not be completed.

### ISSUE THREAD

**Issue by hyuga0410** [alanhg/alfred-workflows#378]
### Describe the bug

[11:51:49.050] ERROR: About Mac[Script Filter] Code 1: /Users/hyuga/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/4599BF94-7BD8-4294-BDB8-EB2950F5F3E9:436:444: execution error: “Finder”遇到一个错误：不能完成此操作。 (-8086)

Sorry, I chose the wrong workflow last time.
The problematic workflow is About Mac.

### Workflow Name

About Mac

### Alfred Version

v1.14

### MacOS Version

macOS 13 Ventura

### Mac Chip

Apple Silicon (like M1, M2)

### MacOS Locale

CN-中文

-----

Workflow Homepage is 👉 [About Mac](https://github.com/alanhg/alfred-workflows/tree/master/about-mac)

**Comment by alanhg** [comment]
方便的话给个Alfred-workflow触发的截图？

我手里没有M1 Mac没法排查。

**Comment by hyuga0410** [comment]
好的大佬，是这个吗？
<img width="1490" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/17693841/9276f5b9-7565-4be6-87fd-d06d19b5755a">

**Comment by alanhg** [comment]
对。
## 进一步排查
打开如下工具，按照我贴的代码，你执行下看看是不是正常，根据issue贴图的报错，需要进一步确定AppleScript,Finder是否正常运行。

![image](https://github.com/alanhg/alfred-workflows/assets/9245110/a39592d0-f131-42d4-8c6f-9b98fb7f997a)

![image](https://github.com/alanhg/alfred-workflows/assets/9245110/cda7a24d-c31f-4d9e-81d5-c50e0991433e)

```applescript
tell application "Finder"
	set username to long user name of (system info)
	display alert username
end tell
```

**Comment by hyuga0410** [comment]
<img width="652" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/17693841/39af2f18-a777-4152-b7bf-5f8d976c658a">
执行正常

**Comment by hyuga0410** [comment]
大佬，不用花费时间去调试了，现在好了，我说下我的情况。
之前都是我报我上面发的错误，刚才我突发奇想，复制了这里面的脚本到脚本编辑器中执行
<img width="779" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/17693841/75c89336-408b-4be3-ba80-a287e4b0202a">
报错变成了：
[14:00:06.963] ERROR: About Mac[Script Filter] Code 1: /Users/hyuga/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/B58C3837-6D95-4B42-AF78-A1B46E4F2722:453:465: execution error: “Finder”遇到一个错误：“访达”正忙。 (-15260)
我想难道是Finder的问题，因为我本机同时在使用QSpace Pro
<img width="116" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/17693841/74174de5-6d5a-429f-8849-ac0b1e8070d3">
，我心想难道是这个冲突了（之前用这个app导也没出现过这种情况，可能是近期升级过这个QSpace吧）？
我试着推出了QSpace，然后试了下About Mac workflow，发现正常了。
于是我又打开了QSpace，再试着运行About Mac，也正常。

不好意思，浪费您时间了，这个应该是我本地环境问题导致的。

**Comment by alanhg** [comment]
> 大佬，不用花费时间去调试了，现在好了，我说下我的情况。 之前都是我报我上面发的错误，刚才我突发奇想，复制了这里面的脚本到脚本编辑器中执行 <img alt="image" width="779" src="https://user-images.githubusercontent.com/17693841/251938878-75c89336-408b-4be3-ba80-a287e4b0202a.png"> 报错变成了： [14:00:06.963] ERROR: About Mac[Script Filter] Code 1: /Users/hyuga/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/B58C3837-6D95-4B42-AF78-A1B46E4F2722:453:465: execution error: “Finder”遇到一个错误：“访达”正忙。 (-15260) 我想难道是Finder的问题，因为我本机同时在使用QSpace Pro <img alt="image" width="116" src="https://user-images.githubusercontent.com/17693841/251938963-74174de5-6d5a-429f-8849-ac0b1e8070d3.png"> ，我心想难道是这个冲突了（之前用这个app导也没出现过这种情况，可能是近期升级过这个QSpace吧）？ 我试着推出了QSpace，然后试了下About Mac workflow，发现正常了。 于是我又打开了QSpace，再试着运行About Mac，也正常。
> 
> 不好意思，浪费您时间了，这个应该是我本地环境问题导致的。

客气了。那issue我关闭了

**Comment by hyuga0410** [comment]
嗯嗯，辛苦大佬了
