### ISSUE TITLE
[Bug]: No profiles returned

### ISSUE THREAD

**Issue by koenbunders** [alanhg/alfred-workflows#381]
### Describe the bug

I have installed the script (thank you), but when I type `chromeprofile` in Alfred, no Chrome profiles are returned.

### Workflow Name

Open Chrome Profile

### Alfred Version

5.1.1

### MacOS Version

macOS 13 Ventura

### Mac Chip

Apple Silicon (like M1, M2)

### MacOS Locale

None

-----

Workflow Homepage is 👉 [Open Chrome Profile](https://github.com/alanhg/alfred-workflows/tree/master/open-chrome-profile)

**Comment by koenbunders** [comment]
Oops... I found out that python3 was not (or not properly) installed. 
Solved the problem by typing `xcode-select --install` in the terminal and let the install run.

**Comment by koenbunders** [comment]
Excellent!
Woudl it be possible to make the script check if there is already a window
for the requested profile open somewhere and if yes, bring that window to
the front (and else open a new window)?
Thanks for the good work!
-- 
*Koen Bunders *

Coöperatie Energized.org U.A. <http://energized.org/>
Versterken van burgerschap in al onze gemeenschappen, te beginnen in en van
organisaties.
+31 (0)6 5163 5503 or +31 (0)8 5130 1795
Linkedin <https://www.linkedin.com/in/kbunders/> | My Roles
<https://app.glassfrog.com/people/16138>

**Comment by alanhg** [comment]
I'll look into it, thank you for your idea.
