### ISSUE TITLE
[Bug]: OCR doesn't work

### ISSUE THREAD

**Issue by xiaoming-w** [alanhg/alfred-workflows#406]
### Describe the bug

<img width="840" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/43328230/887fa213-a0d3-4981-b4c1-33ed021c3701">

### Workflow Name

OCR

### Alfred Version

v5.1.4

### MacOS Version

macOS 14 Sonoma

### Mac Chip

Apple Silicon (like M1, M2)

### MacOS Locale

EN

-----

Workflow Homepage is 👉 [OCR](https://github.com/alanhg/alfred-workflows/tree/master/ocr)

**Comment by xiaoming-w** [comment]
I have installed both pngpaste and node with brew through terminal

**Comment by alanhg** [comment]
> I have installed both pngpaste and node with brew through terminal

![image](https://github.com/alanhg/alfred-workflows/assets/9245110/0896ce4a-7d91-430d-8e52-a0b1d1dfd69e)



I think you need to execute the screenshot command to print it out.

**Comment by xiaoming-w** [comment]
> > I have installed both pngpaste and node with brew through terminal
> 
> ![image](https://private-user-images.githubusercontent.com/9245110/301123706-0896ce4a-7d91-430d-8e52-a0b1d1dfd69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjQ1OTcsIm5iZiI6MTcwNjc2NDI5NywicGF0aCI6Ii85MjQ1MTEwLzMwMTEyMzcwNi0wODk2Y2U0YS03ZDkxLTQzMGQtOGU1Mi1hMGIxZDFkZmQ2OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDUxMTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAwNDNjYjI1ZDQ1YTQxZTQ4NzJiYmUzNGY0YmQ1MmE1MzUwZWY3NGI2OTMwM2ZjYzExOGMyZTIzNWZmNjhiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tVTkQDkfviY7_Xq9N6PvhRW_M8Ay1drUCRsu2FwDuC0)
> 
> I think you need to execute the screenshot command to print it out.

I tried it in the terminal and it didn't work:
<img width="621" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/43328230/8d3211c6-fd6b-4e7b-8941-2559d41abc0c">
I have installed these two packages: pngpaste and node, but somehow they're not in the correct folder

**Comment by alanhg** [comment]
![image](https://github.com/alanhg/alfred-workflows/assets/9245110/707190be-a678-4a33-acc8-6970c03cbbaf)
I think you should print out the location of your commands after installation, so I can understand why it's not in the target path I'm aware of. Otherwise, how would the program know?

which node

which pngpaste

**Comment by xiaoming-w** [comment]
Hi Alan, thanks for the reply, please see below my screenshot:
<img width="621" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/43328230/2223c222-f4ca-4faa-830d-3f4204f6d024">

it seems these two packages were installed in my homebrew folder, what should I do next to have them in the proper location?

Thanks

**Comment by alanhg** [comment]
> Hi Alan, thanks for the reply, please see below my screenshot: <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/43328230/303240266-2223c222-f4ca-4faa-830d-3f4204f6d024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODg5MjgsIm5iZiI6MTcwNzM4ODYyOCwicGF0aCI6Ii80MzMyODIzMC8zMDMyNDAyNjYtMjIyM2MyMjItZjRjYS00ZmFhLTgzMGQtM2Y0MjA0ZjZkMDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NDUyNGU4YjQ5MGRjY2E5NDQwYTBlMTk5MmE0MTE1MDA2YWVlYWVmYWQxNmE5NmFhOGE5NWNhNDRmY2VhNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GLCRoVLO157UVEXLoe7Bx8IxdPW3YCj5ZnwT0YUgAdA">
> 
> it seems these two packages were installed in my homebrew folder, what should I do next to have them in the proper location?
> 
> Thanks

I have updated the version, I'll try installing it, and if there are still issues, I'll reopen the issue.

**Comment by xiaoming-w** [comment]
I've updated to your latest version, but it still doesn't seem to work.

I added it to the Shortcuts, but couldn't paste it for some reason, and I didn't see these two windows as in your homepage when I was adding OCR to the Shortcuts:
<img width="459" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/43328230/becd0a22-9ca3-4ff5-ad1f-eee128b29c15">

when I double click on the newly added OCR shortcut, I see this window:
<img width="1236" alt="image" src="https://github.com/alanhg/alfred-workflows/assets/43328230/7b60e7bf-58fc-4d5e-9de8-3a3d81283334">

**Comment by alanhg** [comment]
After the first OCR trigger, you will be prompted to install. After triggering OCR again, select the screen area and press Enter to perform OCR and retrieve the text. There will be a prompt for permission, just keep clicking allow, and you will not be prompted again in future use. Using Alfred workflow inevitably requires understanding the workflow.

**Comment by xiaoming-w** [comment]
so I reinstalled the OCR shorcut, and clicked "allow" on the first privacy window, but I did not see the second privacy window.  
The OCR tool still doesn't work. After selecting the text on the image, there isn't a text editor popping up like in your gif presentation, and I could neither paste the text anywhere else.
