### ISSUE TITLE
surge 不能显示所以的配置文件Profiles

### ISSUE THREAD

**Issue by llity** [alanhg/alfred-workflows#44]
无法显示配置文件，谢谢

**Comment by llity** [comment]
`ERROR: Surge[Script Filter] Code 1: /Users/xxx/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.1CB5FB48-FA7E-4E10-AD3A-6E7892710A1A/profiles.js:8
    arg: utils.joinMultiArg(`switchProfile`, item)
         ^

ReferenceError: utils is not defined
    at /Users/xxx/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.1CB5FB48-FA7E-4E10-AD3A-6E7892710A1A/profiles.js:8:10
    at Array.map (<anonymous>)
    at /Users/xxx/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.1CB5FB48-FA7E-4E10-AD3A-6E7892710A1A/profiles.js:6:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by alanhg** [comment]
已更新新版，下载试试。

**Comment by llity** [comment]
> 已更新新版，下载试试。

可以使用了。希望能加入自动更新，OneUpdater

**Comment by alanhg** [comment]
> > 已更新新版，下载试试。
> 
> 可以使用了。希望能加入自动更新，OneUpdater

当前自动更新难做的根本问题在于Alfred 软件层面没有给予很好的口子支持。

但这是个好的建议，我创建个issue来追踪下。
https://github.com/alanhg/alfred-workflows/issues/46


当前我能想到的折衷办法，
1. 将workflow本身封装为npm package，比如叫@stacker/alfred-surge
2. 用户在自己Mac上配置自动更新package即可/用户手动npm install @stacker/alfred-surge
