### ISSUE TITLE
workflow auto-update?

### ISSUE THREAD

**Issue by alanhg** [alanhg/alfred-workflows#46]
## 方案1
- 将workflow本身封装为npm package，比如叫@stacker/alfred-surge
- 用户在自己Mac上配置自动更新package即可/用户手动npm install @stacker/alfred-surge
## 方案2
- 增加workflow设定，自动更新检测
- 开启更新检测的情况下，用户唤起workflow时进行检测，如果有新版，则提供选项，让用户选择更新
- 用户回车选择更新-自动下载workflow-自动安装
- 用户只需要手动继续选择安装即可

当前倾向于方案2，可行且体验较好，唯一考虑是对于非科学上网环境用户，更新检测会存在网速超时/阻塞。因为当前新版发布在GitHub仓库。

**Comment by llity** [comment]
能用 [OneUpdater](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) 很方便。

**Comment by alanhg** [comment]
> 能用 [OneUpdater](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) 很方便。

看了下源码，这种本质还是个手动更新，我考虑下，个人觉得集成在对应workflow比较合适而不是在另一个workflow下进行管理。

**Comment by llity** [comment]
@alanhg 就是集成到每个workflow里面，每次使用该workflow对自动检测更新下载并打开，需要手动确认点击更新。

**Comment by alanhg** [comment]
1. 现在已经开发了 @stacker/alfred-utils 来做workflow的更新检测支持。
2. Surge作为第一个接入自动更新的workflow，后续会跟许需求逐步都接入支持，同时也可以完善当前工具库的不足。


## 效果如下

![image](https://user-images.githubusercontent.com/9245110/130351317-6a1ae1d7-9929-4ba5-a7e4-b046d395389d.png)

## 使用指南

![image](https://user-images.githubusercontent.com/9245110/130351370-e58a1b0b-ff32-49c8-b9b2-4cc26617b715.png)

- `check_update`为更新开关，如果设置为非true，比如false，则唤起workflow时不会再进行更新检测
-`remote_info_list_url`为远程workflow/info.plist文件地址，用于检测版本信息，用来与本地进行比对，确认是否有新版
- `remote_workflow_url`为远程workflow下载地址

在新版workflow安装时，会直接内置了目前的远程地址，当然也可以自行修改到别的托管地址，一般不建议改动。

需要注意的是，GitHub国内网络访问并不快/稳定，如果有条件科学上网最佳。
