### ISSUE TITLE
Surge workflow: policyGroups 无法展现进行选择

### ISSUE THREAD

**Issue by llity** [alanhg/alfred-workflows#47]
只能展开到这里
![image](https://user-images.githubusercontent.com/11771112/129560549-d62bb8fa-e9e2-414a-ab73-19d357108869.png)
如下图：应该可以展开后进行选择
![image](https://user-images.githubusercontent.com/11771112/129560835-1347a80c-9059-46e8-88db-ad79a166e763.png)

**Comment by llity** [comment]
这里同时也能关键词过滤基本完美了。不知道Dashboard能否在顶级列表中调用？

**Comment by alanhg** [comment]
![image](https://user-images.githubusercontent.com/9245110/130357425-59e4569e-7cc7-44f5-88f7-d74cc1125325.png)

同时支持搜索过滤

**Comment by llity** [comment]
“policyGroups” 不支持过滤。还有个问题：能不能记住我上一次选择的项目，就是最近打开的项目按时间顺序排列，而不是每次打开默认的顺序呢？这样方便打开常用的项目。
谢谢

**Comment by alanhg** [comment]
@llity 我更新了一版，支持了下。

另外，如果是多次操作才可以进入的选项，我个人觉得利用Surge软件操作会比这个高效，Alfred在多次列表交互选择上效率并不高。

关于这个idea
> 能不能记住我上一次选择的项目，就是最近打开的项目按时间顺序排列，而不是每次打开默认的顺序呢？这样方便打开常用的项目。

是个不错的idea，但是实用性上不见得高，因为毕竟有了搜索，且Surge中比如policy-group存在编辑修改，其实是会变的，只是比如入口的操作选项列表，是固定的，倒是可以做个最近访问顺序排序下。

但还是那句话，因为有了搜索，其实这个并没有多大意义了。

**Comment by llity** [comment]
@alanhg 明白了。这样来说，如果直接促发workflow后，输入关键词就能搜索所有的下级菜单后操作不就更方便了。不再需要一级一级的打开。而且不能返回上一级，使用起来每次都一层层才能找到需要的配置选项确实不方便。

**Comment by alanhg** [comment]
对，当前的搜索支持针对当前的级别，

- 返回上一级这个是个问题，可以做下支持，这是个实际的痛点，我想下怎么实现比较好。
- 搜索是不是可以直接搜索下级的所有菜单，这个本身是个度的问题，因为所有的数据都要提前获取到必然降低了速度，另外也会导致搜索过滤存在准头的问题，毕竟rule等信息那种数据很容易命中，产生了干扰。

我觉得当前这种搜索其实还可以满足需求，可以再用用看看。
