### ISSUE TITLE
audio switch doesn't work in Monterey

### ISSUE THREAD

**Issue by nengqi** [alanhg/alfred-workflows#61]
![image](https://user-images.githubusercontent.com/32950454/138995479-d81df504-933d-4076-ba4c-bc68d4bcc91d.png)
选择了指定设备后切换不过去
放automator里运行，显示
![image](https://user-images.githubusercontent.com/32950454/138995605-6fea6ce7-b6f3-4bc4-bbe8-00ea8039f2f2.png)

**Comment by Obadiahcruz** [comment]
same issue here!

**Comment by alanhg** [comment]
> same issue here!

download the latest and have a try.
