### ISSUE TITLE
Input/Output Sets

### ISSUE THREAD

**Issue by christianmagill** [alanhg/alfred-workflows#63]
Thanks for your work on this workflow! My computer keeps assuming I want to use my monitor as a speaker whenever I dock. This workflow lets me keep a bit of my sanity.

What do you think about the possibility of input/output sets?

Typically when I'm using my laptop undocked, I want to use the internal speaker and microphone. However, when I dock I switch to a different speaker and microphone.

It would be cool to be able to create sets for input and output that could be swapped in one go.

**Comment by alanhg** [comment]
1. Alfred can't do. because Alfred can do anything by your input, it can't auto do something.
2. Hammerspoon can meet your demand. http://www.hammerspoon.org/docs/hs.audiodevice.watcher.html
