### ISSUE TITLE
Feature suggestion: change camera input

### ISSUE THREAD

**Issue by a-rock-lobster** [alanhg/alfred-workflows#64]
Thank you for the work flow. Very useful.

I had the thought that a useful addition would be video input. For example, selecting between additional webcams and camera's in second monitors. 

I have no tech expertise so I cannot offer any help.

Thanks again,

Edit: grammar

**Comment by alanhg** [comment]
> Thank you for the work flow. Very useful.
> 
> I had the thought that a useful addition would be video input. For example, selecting between additional webcams and camera's in second monitors.
> 
> I have no tech expertise so I cannot offer any help.
> 
> Thanks again,
> 
> Edit: grammar

I currently don’t have an external camera device, so I need to find one to try to know how to do it

**Comment by alanhg** [comment]
It took a while to look at it, and it didn’t provide any interface at the macOS level for us to choose a different device.

It must be a command-line tool/App to assist in the implementation. At the same time, I personally do not have this requirement, so I want to close the issue

**Comment by alanhg** [comment]
1. I have updated the workflow, you can view the camera device list.
   
![image](https://user-images.githubusercontent.com/9245110/142719854-141e4e76-cbfa-4f96-8f01-bb8625a102ef.png)

2. But you can't switch camera devices. According to my investigation, different apps do not use the same settings, so you can only set them manually in different apps.

**Comment by a-rock-lobster** [comment]
Cheers! 
I think you're right on the app specific settings. There doesn't seem to be system default.
Thanks again,
