### ISSUE TITLE
can not preview with Shift

### ISSUE THREAD

**Issue by gengxuelei** [alanhg/alfred-workflows#7]
![image](https://user-images.githubusercontent.com/11707936/91541998-be24ea80-e94f-11ea-8332-6749af889706.png)

**Comment by alanhg** [comment]
@gengxuelei 谢谢提问，我抽空看下。平时不怎么关注issue，欢迎邮件，或者直接加我微信`见readme`。

**Comment by gpfworld** [comment]
+1
