### ISSUE TITLE
Monterey Support Planned?

### ISSUE THREAD

**Issue by EttVenter** [alanhg/alfred-workflows#73]
Heya!

Any plans to add Monterey Support? The workflow seems to do nothing at all when executed. 

Thanks for your hard work!

**Comment by alanhg** [comment]
which workflow？
what's error?

**Comment by EttVenter** [comment]
Hey!

The airdrop workflow. There's no error, but when I try to use it, literally nothing happens. Any idea why?

Ett Venter
Photographer - Instructor - Speaker
082 424 4222 | www.ettventer.com

**Comment by alanhg** [comment]
Not knowing the error and therefore unable to judge, I cannot proceed further

**Comment by EttVenter** [comment]
I'm not sure if I was unclear before, but there's no error. There's just nothing that happens.

Ett Venter
Photographer - Instructor - Speaker
082 424 4222 | www.ettventer.com

**Comment by chrisspiegl** [comment]
I just installed this workflow and got this error message:

```
ERROR: Airdrop[Run Script] /Users/chrisspiegl/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/26620927-305E-4B38-BDF2-A5C95305533C:876:917: execution error: System Events got an error: Can’t get button 1 of toolbar 1 of window 1 of process "Finder" whose description = "Share". Invalid index. (-1719)
```

I am on M1 Apple Silicone / Monterey / 12.2 Beta (21D5025f)

**Comment by EttVenter** [comment]
Yeah, this still isn’t working for me. Any idea why? I tried it now, and upon actioning the “Share Files with Airdrop” action in the files actions menu, nothing happens.

I don’t mean to be a nag, and I’d totally understand if you don’t want to try to figure this out - you don’t owe me anything, lol. I just use airdrop a shit ton, so this would be super useful.

Thanks!

Ett Venter
Photographer - Instructor - Speaker
082 424 4222 | www.ettventer.com

**Comment by chrisspiegl** [comment]
@EttVenter I am not the creator of this workflow but I do have this on my todo list as well. Just haven't found the time up to this point. I'll post an update here when I do (or if @alanhg fixes it).

**Comment by EttVenter** [comment]
Amazing, thank you Chris!

Ett Venter
Photographer - Instructor - Speaker
082 424 4222 | www.ettventer.com

**Comment by alanhg** [comment]
Just have a try for the latest workflow-airdrop.

I found ok on monterey.

**Comment by chrisspiegl** [comment]
Hi @alanhg, that's great to hear.
Could you update the packaged alfredworkflow files as well?
Those seem to be the old ones still.

Thank you 🌸

**Comment by alanhg** [comment]
current is latest. error or not work？

**Comment by chrisspiegl** [comment]
I tested with this file: https://github.com/alanhg/alfred-workflows/blob/master/airdrop/Airdrop.alfredworkflow

It is 3 Months old (and the `src` folder in the same folder is 11 days old) with a bunch of changes.

Here is the error message from the Alfred Debug Console:

```
[14:46:18.622] ERROR: Airdrop[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.6F5919E2-FA6A-4A2C-84B9-7892813EF254%3EE132D993-DFA1-4D18-8E8F-1E19D7073AE2)] /Users/..../Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/66089578-8A24-46F4-A975-654013E748D0:876:917: execution error: System Events got an error: Can’t get button 1 of toolbar 1 of window 1 of process "Finder" whose description = "Share". Invalid index. (-1719)
```

**Comment by chrisspiegl** [comment]
1. Mac version and language: 12.3 (M1 Max / English)
1. Alfred version: 4.6.5 [1298]
1. Workflow version: v1.7

When I open Alfred and type `airdrop` and hit `Enter` I simply get a notification that i should select a file or url. It does not give me an option to filter for file or anything. Not sure what that specific `Keyword` Input is supposed to do.

When I have a url in the clipboard it does not show the notification but also nothing happens.

When I open the `Share Files with…` action on a `File Action` in Alfred and hit enter, I get the error message I posed before:

```
Airdrop[File Action] Passing output '/Users/chrisspiegl/Desktop/a.jpg' to Run NSAppleScript
Airdrop[Run NSAppleScript] Processing complete
Airdrop[Run NSAppleScript] Passing output 'en_DE' to Arg and Vars
Airdrop[Arg and Vars] Processing complete
Airdrop[Arg and Vars] Passing output 'en_DE' to Conditional
Airdrop[Conditional] Processing complete
Airdrop[Conditional] Passing output 'en_DE' to Run Script
ERROR: Airdrop[Run Script] /Users/chrisspiegl/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/66089578-8A24-46F4-A975-654013E748D0:876:917: execution error: System Events got an error: Can’t get button 1 of toolbar 1 of window 1 of process "Finder" whose description = "Share". Invalid index. (-1719)
```

**Comment by alanhg** [comment]
maybe en_DE diff from en_US.

can you try en_US?

**Comment by chrisspiegl** [comment]
I switched the language and region to EN USA

Same error from what I can tell:

```
Airdrop[Arg and Vars] Processing complete
Airdrop[Arg and Vars] Passing output 'en_US' to Conditional
Airdrop[Conditional] Processing complete
Airdrop[Conditional] Passing output 'en_US' to Run Script
ERROR: Airdrop[Run Script] /Users/chrisspiegl/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/66089578-8A24-46F4-A975-654013E748D0:876:917: execution error: System Events got an error: Can’t get button 1 of toolbar 1 of window 1 of process "Finder" whose description = "Share". Invalid index. (-1719)
```

Here is a screenshot of the Finder Menu:
<img width="296" alt="Capture 2022-04-07 at 5 04 25 PM" src="https://user-images.githubusercontent.com/1096384/162230965-0c92235c-8b6e-4b5a-8f32-e75bd9408ee4.png">

**Comment by alanhg** [comment]
![image](https://user-images.githubusercontent.com/9245110/162236954-e717dd1c-eaf4-4498-bb4a-1ec5eb50a5f4.png)

you see here.

**Comment by chrisspiegl** [comment]
Interesting, why not make it depend on the menu bar item?
I personally have all the finder toolbar things hidden to have the design be clean.
The Menubar feels like it would be more reliable to depend on?
