### ISSUE TITLE
icu4C version error.

### ISSUE THREAD

**Issue by qiaoliang** [alanhg/alfred-workflows#92]
Hi Alan, thanks for your sharing. 

I got errors from Giphy caused by the version of icu4c installed on my mac, which is 70.1.

the error shows that it needs 69.

How could I fix it?

error 👍 [23:19:47.205] ERROR: Giphy[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.96BFA19D-F843-4508-87BF-F9BEF06BE8F0%3E63178F25-7718-4704-A5A4-A092D70B1D7A)] Code 6: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.69.dylib

**Comment by alanhg** [comment]
> Hi Alan, thanks for your sharing.
> 
> I got errors from Giphy caused by the version of icu4c installed on my mac, which is 70.1.
> 
> the error shows that it needs 69.
> 
> How could I fix it?
> 
> error 👍 [23:19:47.205] ERROR: Giphy[Script Filter] Code 6: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.69.dylib

这里是workflow集合，建议贴下Mac系统版本，workflow名称及版本。

**Comment by alanhg** [comment]
有进一步具体信息再reopen.
